#!/bin/bash

export SERVER_PORT=7701
export CONTAINER_SERVER_PORT=30721

export JMX_PORT=9001
export EXT_JMX_PORT=30002
export RMI_PORT=30012
export EXT_RMI_PORT=30012

export JGROUPS_RAFT_MEMBERS=A,B,C
export JGROUPS_RAFT_NODE_NAME=B

docker run -d --name eta-cache2 \
 -e SERVER_PORT=${SERVER_PORT} \
 -e JMX_PORT=${JMX_PORT} \
 -e RMI_PORT=${RMI_PORT} \
 -e JGROUPS_RAFT_MEMBERS=${JGROUPS_RAFT_MEMBERS} \
 -e JGROUPS_RAFT_NODE_NAME=${JGROUPS_RAFT_NODE_NAME} \
 -v /home/super/var/jgroups/.RAFT:/opt/.RAFT \
 -p ${CONTAINER_SERVER_PORT}:${SERVER_PORT} \
 -p ${EXT_JMX_PORT}:${JMX_PORT} \
 -p ${EXT_RMI_PORT}:${RMI_PORT} \
 localhost:32000/eta-cache:latest
